set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN M5 [get_ports {key_in[0]}]
set_property PACKAGE_PIN N4 [get_ports {key_in[3]}]
set_property PACKAGE_PIN M4 [get_ports {key_in[2]}]
set_property PACKAGE_PIN P5 [get_ports {key_in[1]}]
set_property PACKAGE_PIN G11 [get_ports clk]
set_property PACKAGE_PIN B6 [get_ports rst]
set_property PACKAGE_PIN F12 [get_ports tx]

set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN E12 [get_ports rx]
